# Generated by Django 4.0.5 on 2022-07-05 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0005_alter_movie_options_tag_listings_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='created_by',
            field=models.ForeignKey(default=uuid.UUID('02cc3697-ab11-46d2-aff0-8e75115b61da'), on_delete=django.db.models.deletion.CASCADE, related_name='created_genres', related_query_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='created_by',
            field=models.ForeignKey(default=uuid.UUID('02cc3697-ab11-46d2-aff0-8e75115b61da'), on_delete=django.db.models.deletion.CASCADE, related_name='created_listings', related_query_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=uuid.UUID('02cc3697-ab11-46d2-aff0-8e75115b61da'), on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', related_query_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(default=uuid.UUID('02cc3697-ab11-46d2-aff0-8e75115b61da'), on_delete=django.db.models.deletion.CASCADE, related_name='created_movies', related_query_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
