# Generated by Django 4.0.5 on 2022-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_listings_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='episode_id',
            new_name='episode_number',
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'MOVIE'), ('show', 'SHOW')], default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='season number'),
        ),
    ]
