# Generated by Django 4.0.5 on 2022-07-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_rename_episode_id_listing_episode_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='content_descriptions',
            new_name='content_description',
        ),
    ]
