# Generated by Django 4.0.5 on 2022-07-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userprofile_id_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uuid',
            new_name='id',
        ),
    ]
